services:
  - type: web
    name: calculator
    env: node
    plan: free
    buildCommand: npm install && npm --prefix admin-server install
    startCommand: npm run admin:start
    envVars:
      - key: NODE_ENV
        value: production
